###

# Login request
POST http://3.22.70.164:3000/login
Content-Type: application/json

{
    "email": "mrthnx@icloud.com"
}

###

# Registration request
POST http://3.22.70.164:3000/register
Content-Type: application/json

{
    "email": "mrthnx@icloud.com"
}

###

# Retrieve all tasks
GET http://3.22.70.164:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ydGhueEBpY2xvdWQuY29tIiwiaWQiOjEsImlhdCI6MTc0MjYxMjQwNywiZXhwIjoxNzQyNjE2MDA3fQ.W2ttOfyMXeiBGf7yqItsix85F32QIPAtpK_ABtRkBmg

###

# Retrieve a specific task by ID
GET http://3.22.70.164:3000/tasks/6
Authorization: Bearer <token>

###

# Create a new task
POST http://3.22.70.164:3000/tasks
Authorization: Bearer <token>
Content-Type: application/json

{
    "title": "test",
    "description": "test"
}

###

# Update an existing task by ID
PUT http://3.22.70.164:3000/tasks/6
Authorization: Bearer <token>
Content-Type: application/json

{
    "title": "test 1",
    "description": "test"
}

###

# Delete a task by ID
DELETE http://3.22.70.164:3000/tasks/7
Authorization: Bearer <token>


