###

# Login request
POST http://3.22.70.164:3000/login
Content-Type: application/json

{
    "email": "mrthnx@icloud.com"
}

###

# Registration request
POST http://3.22.70.164:3000/register
Content-Type: application/json

{
    "email": "mrthnx@icloud.com"
}

###

# Retrieve all tasks
GET http://3.22.70.164:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ydGhueEBpY2xvdWQuY29tIiwiaWQiOjEsImlhdCI6MTc0MjYxODczOCwiZXhwIjoxNzQyNjIyMzM4fQ.PvJuFH9qZuhcPkxD4Yn7SbcR6jPqpnanpCCg8NLuNQk

###

# Retrieve a specific task by ID
GET http://3.22.70.164:3000/tasks/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ydGhueEBpY2xvdWQuY29tIiwiaWQiOjEsImlhdCI6MTc0MjYxMjQwNywiZXhwIjoxNzQyNjE2MDA3fQ.W2ttOfyMXeiBGf7yqItsix85F32QIPAtpK_ABtRkBmg
###

# Create a new task
POST http://3.22.70.164:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ydGhueEBpY2xvdWQuY29tIiwiaWQiOjEsImlhdCI6MTc0MjYyMDM4OCwiZXhwIjoxNzQyNjIzOTg4fQ.dhoqiHJmG-60Lz98ZzXSyE73TwdbJ3WEUpQVQACCi1g
Content-Type: application/json

{
    "title": "test lorem ipsum dolor sit amet",
    "description": "test lorem ipsum dolor sit amet adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"
}

###

# Update an existing task by ID
PUT http://3.22.70.164:3000/tasks/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ydGhueEBpY2xvdWQuY29tIiwiaWQiOjEsImlhdCI6MTc0MjYyNjQwMiwiZXhwIjoxNzQyNjMwMDAyfQ.8OXy7YqnBBqer648Dktdg0jELW7TK-L6MpKCFkMITHg
Content-Type: application/json

{
    "title": "test 1",
    "description": "test",
    "isCompleted": null
}

###

# Delete a task by ID
DELETE http://3.22.70.164:3000/tasks/7
Authorization: Bearer <token>

### 

# PATCH 
PATCH http://3.22.70.164:3000/tasks/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ydGhueEBpY2xvdWQuY29tIiwiaWQiOjEsImlhdCI6MTc0MjYxODczOCwiZXhwIjoxNzQyNjIyMzM4fQ.PvJuFH9qZuhcPkxD4Yn7SbcR6jPqpnanpCCg8NLuNQk
